### ISSUE TITLE
Permission trouble

### ISSUE THREAD

**Issue by ruvasik** [Kwadz/speed-docker-for-mac#3]
App can't write log & cache, permission denied.
Experiments with mutagen config permissions did not give results.

**Comment by Kwadz** [comment]
This seems not to be a Mutagen configuration related issue. I think it is more a permission issue between the configured user of the web server and the user that owns the cache/log files. 

What is the user of the web server? You can check it with `ps aux | grep nginx`
What is the owner of the cache/log files? A simple `ls -l` on the related folders will give the info.

**Comment by ruvasik** [comment]
I checked owners & permission - this is reproduced with all variations

**Comment by ruvasik** [comment]
I use 1 docker-compose file — need I put both variants for www?
```
  php:
    build:
      context: php
      dockerfile: Dockerfile
      - ../www:/srv/www
...
      - codebase:/srv/www
    volumes:
```
or only with codebase?
